### PR TITLE
WCF host service exception handling

### LINKED ISSUE #73: Wcf channel broken and not able to auto recover after unhanded exception thrown on server
System.ServiceModel.ProtocolException

"This channel can no longer be used to send messages as the output session was auto-closed due to a server-initiated shutdown. Either disable auto-close by setting the DispatchRuntime.AutomaticInputSessionShutdown to false, or consider modifying the shutdown protocol with the remote server."

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.PrepareCall(ProxyOperationRuntime operation, Boolean oneway, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at PowerShellTools.Common.ServiceManagement.DebuggingContract.IPowershellDebuggingService.SetRunspace(Boolean overrideExecutionPolicy)
   at PowerShellTools.DebugEngine.Engine.Execute() in c:\Users\zhiyd\Documents\GitHub\outproc_dbg_local\poshtools\PowerShellTools\DebugEngine\Engine.cs:line 114
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

### PR DESCRIPTION
**Pull request by ericdevg**
Also fixed #73
@HuanhuanSunMSFT @AndreSayreMSFT @adamdriscoll

### CODE REVIEW

File: PowerShellTools.HostService/PowershellServiceHostBehavior.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+using System.Threading.Tasks;
+
+namespace PowerShellTools.HostService
+{
+    /// <summary>
+    /// In WCF, unhandled excpetion crashes the servcie, leaving the channel into fault state, which is basically requiring client to re-instantiate proxy in order to continue using the service.
+    /// As a result, WCF provides the ability to configure a service to return information from unhandled exceptions.
+    /// This is implemetaion of the generic error handler for entire powershell wcf services, by exposing it as a service behavior attribute, so that it is developer friendly
+    /// </summary>
+    class PowershellServiceHostBehavior : Attribute, IErrorHandler, IServiceBehavior
```
Comment (ASayre) [inline PowerShellTools.HostService/PowershellServiceHostBehavior.cs]: nit: Access modifier on class and branding/capitalization

File: PowerShellTools.HostService/ServiceManagement/IntelliSense/PowershellIntelliSenseService.cs [hunk 2]
```diff
@@ -10,6 +10,7 @@ namespace PowerShellTools.HostService.ServiceManagement
     /// <summary>
     /// Represents a implementation of the service contract.
     /// </summary>
+    [PowershellServiceHostBehavior]
```
Comment (ASayre) [inline PowerShellTools.HostService/ServiceManagement/IntelliSense/PowershellIntelliSenseService.cs]: nit: Branding capitalization

File: PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+using System.Collections.Generic;
+using System.Linq;
+using System.Runtime.Serialization;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace PowerShellTools.Common.ServiceManagement
+{
+    [DataContract]
+    class PowershellHostServiceExceptionDetails
```
Comment (ASayre) [inline PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs]: double nit: access modifier & branding capitalization :)

File: PowershellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingService.cs [hunk 4]
```diff
@@ -222,22 +216,16 @@ public void ExecuteDebuggingCommand(string debuggingCommand)
         public void SetBreakpoint(PowershellBreakpoint bp)
         {
             ServiceCommon.Log("Setting breakpoing ...");
```
Comment (ASayre) [inline PowershellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingService.cs]: spelling nit 'breakpoing'

File: PowerShellTools.HostService/PowershellServiceHostBehavior.cs [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+using System.ServiceModel.Channels;
+using System.ServiceModel.Description;
+using System.ServiceModel.Dispatcher;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace PowerShellTools.HostService
+{
+    /// <summary>
+    /// In WCF, unhandled excpetion crashes the servcie, leaving the channel into fault state, which is basically requiring client to re-instantiate proxy in order to continue using the service.
```
Comment (ASayre) [inline PowerShellTools.HostService/PowershellServiceHostBehavior.cs]: spelling nits: excpetion / servcie

File: PowerShellTools.HostService/PowershellServiceHostBehavior.cs (hunk 1 above)
Comment (ASayre) [inline PowerShellTools.HostService/PowershellServiceHostBehavior.cs]: .NET Attribute naming guidelines recommend PowerShellServiceHostBehaviorAttribute.  (It can/will still be used as [PowerShellServiceHostBehavior] )

Comment (ASayre) [inline PowerShellTools.HostService/PowershellServiceHostBehavior.cs]: We should be explicit about the [AttributeUsage].  It looks like this is only applicable on Classes.  If so:  [AttributeUsage(AttributeTargets.Class)], otherwise it can be applied on all by default

File: PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+    {
+        public static readonly PowershellHostServiceExceptionDetails Default = new PowershellHostServiceExceptionDetails();
+
+        [DataMember]
+        public String Message { get; private set; }
+
+        public PowershellHostServiceExceptionDetails()
+        {
+            this.Message = "There is a problem in the powershell host service.";
```
Comment (ASayre) [inline PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs:20]: If this exception message can ever be seen by a user, we should make localizable

File: PowerShellTools.HostService/PowershellServiceHostBehavior.cs (hunk 1 above)
Comment (ericdevg) [inline PowerShellTools.HostService/PowershellServiceHostBehavior.cs]: Fixed all

File: PowerShellTools.HostService/ServiceManagement/IntelliSense/PowershellIntelliSenseService.cs (hunk 2 above)
Comment (ericdevg) [inline PowerShellTools.HostService/ServiceManagement/IntelliSense/PowershellIntelliSenseService.cs]: Fixed.

File: PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs (hunk 3 above)
Comment (ericdevg) [inline PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs]: Public sealed

File: PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs (hunk 6 above)
Comment (ericdevg) [inline PowershellTools.Common/ServiceManagement/PowershellHostServiceExceptionDetails.cs:20]: So far we don't show it to end user, just for internal logging purpose. However we may need look over the entire project to see if there is anything needs to be localized, maybe March? Anyway I'd like to enter a task for localization work, if there is not yet one.

File: PowershellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingService.cs (hunk 4 above)
Comment (ericdevg) [inline PowershellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingService.cs]: Thanks. Fixed.
