### PR TITLE
Fix a method missing exception due to version difference

### LINKED ISSUE #667: There is a problem in the PowerShell host service error after deploying with an Azure Resource Group project on Windows 7
On Windows 7 x64:
- Install Visual Studio 2015
- Install Web Platform Installer (Web PI) from https://www.microsoft.com/web/downloads/platform.aspx
- Using Web PI, install Microsoft Azure SDK for .NET (VS 2015) - 2.7
- Using Web PI, install Microsoft Azure PowerShell
- Install PowerShell Tools for Visual Studio 2015 from https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597
1.  Open Visual Studio 2015
2.  Create a new C# Cloud/Azure Resource Group project, using the Web app template
3.  Open the WebSite.param.dev.json file under the Templates folder
4.  Change the siteName from null to "MyWebSite", hostingPlanName from null to "Dev" and siteLocation from null to "West US"
5.  Right-click the AzureResourceGroup node, choose Deploy -> New Deployment...
6.  In the Deploy to Resource Group dialog, sign in with an account that has an associated Microsoft Azure subscription, if not already
7.  Select a subscription
8.  Use the Resource Group dropdown to create a new one
9.  Click Deploy

Result:
An error occurs saying, "There is a problem in the PowerShell host service."

### PR DESCRIPTION
**Pull request by HuanhuanSunMSFT**
Fixes #667 
@EricMSFT @MrayerMSFT @jinglou- @AndreSayreMSFT

### CODE REVIEW

File: PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs [hunk 1]
```diff
@@ -103,8 +103,18 @@ private void DebuggerFinished()
         {
             ServiceCommon.Log("DebuggerFinished");
 
-            ClearBreakpoints();
-            _psBreakpointTable.Clear();
+            try
```
Comment (ericdevg) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs]: I thought by wrapping up the v4+ api into separate method would just solve the problem, if we do want to make the clearbreakpoint not throw, I would do that(try/catch) inside clearbreakpoint function itself.

File: PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs [hunk 2]
```diff
@@ -135,6 +145,16 @@ private void DebuggerFinished()
...
         }
 
+        private bool IsDebuggerActive(System.Management.Automation.Debugger debugger)
+        {
+            if (_installedPowerShellVersion >= RequiredPowerShellVersionForRemoteSessionDebugging)
+            {
+                return debugger.IsActive;
+            }
+
+            return false;
```
Comment (ericdevg) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs:143]: Let's put a short comment here about why we are returning false here for v4- versions.

**Comment by MrayerMSFT** [comment]
Added a quick fix for another bug since it deals with the same method. Code looks good to me, but suggestion from @EricMSFT is not without merit.
