### PR TITLE
Bug Fix #174: "Add-AzureAccount window poped up behind VS"

### LINKED ISSUE #174: ADAL & Credential Windows have sometimes appear behind Visual Studio
Try Add-AzureAccount or Get-Credential; sometimes the auth dialog appears behind Visual Studio, with no obvious prompt.

### PR DESCRIPTION
**Pull request by ericdevg**
#174

@AndreSayreMSFT @HuanhuanSunMSFT @bmoore-msft @Microsoft/poshtools 

Add-AzureAccount pops its own window for authentication, there is nothing we can pipe back to VS to operate in this case, so we have to put remote host process window(invisible) on top so that the new window from the process can be presented on top of VS.

In order to obtain the invisible window handle, you have to visible it first and then hide it. MSDN: https://msdn.microsoft.com/en-us/library/system.diagnostics.process.mainwindowhandle(v=vs.110).aspx

### CODE REVIEW

File: PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs [hunk 1]
```diff
@@ -50,6 +63,12 @@ public static PowershellHostProcess CreatePowershellHostProcess()
             bool success = readyEvent.WaitOne();
             readyEvent.Close();
 
+            MakeTopMost(powershellHostProcess.MainWindowHandle);
```
Comment (ASayre) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs:64]: What happens if these are called when success is false?

File: PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs [hunk 2]
```diff
@@ -32,13 +45,13 @@ public static PowershellHostProcess CreatePowershellHostProcess()
 
             powershellHostProcess.StartInfo.Arguments = hostArgs;
             powershellHostProcess.StartInfo.FileName = path;
-#if DEBUG
+//#if DEBUG
```
Comment (ASayre) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs]: Do we want to cleanup the commented out stuff?

File: PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs [hunk 3]
```diff
@@ -13,6 +14,18 @@ namespace PowerShellTools.ServiceManagement
...
+        [DllImport("user32.dll", SetLastError = true)]
+        private static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int W, int H, uint uFlags);
+
+        [DllImport("user32.dll")]
+        private static extern bool ShowWindow(IntPtr hWnd, int nCmdShow); 
+
+        private static readonly IntPtr HWND_TOPMOST = new IntPtr(-1);
+        private const UInt32 SWP_NOSIZE = 0x0001;
+        private const UInt32 SWP_NOMOVE = 0x0002;
+        private const UInt32 TOPMOST_FLAGS = SWP_NOMOVE | SWP_NOSIZE;
```
Comment (ASayre) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs]: uint instead of UInt32 [Yes, they're aliased, but consistency :) SetWindowPos uses uint as signature]

Comment (ASayre) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs]: Do we also want SWP_NOACTIVATE, or no?  [Does anything else lose focus/activation, even though we're hidden?]

File: PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs (hunk 1 above)
Comment (ericdevg) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs:64]: That runs fine as you will get handle = 0, which ends up a null operation.

File: PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs (hunk 2 above)
Comment (ericdevg) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs]: Ah sure.

File: PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs (hunk 3 above)
Comment (ericdevg) [inline PowerShellTools/ServiceManagement/PowershellHostProcessHelper.cs]: Good point, although VS seems like holds the focus every time it runs. But should set the flag just to be safe.

**Comment by ASayre** [comment]
Looks good!
