### PR TITLE
Fix dte init

### LINKED ISSUE #152: $dte doesn't show up in intellisense until first use [both REPL & Editor]
image

image

### PR DESCRIPTION
**Pull request by ASayre**
@EricMSFT @HuanhuanSunMSFT @adamdriscoll 

Fixes #152

### CODE REVIEW

**Comment by ericdevg** [comment]
Looks good

File: PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs [hunk 1]
```diff
@@ -11,15 +7,22 @@
...
+using PowerShellTools.Common.Debugging;
+using PowerShellTools.Common.ServiceManagement.DebuggingContract;
 
 namespace PowerShellTools.HostService.ServiceManagement.Debugging
 {
     /// <summary>
     /// Utility functions for powershell debugging service
     /// </summary>
-    public partial class PowershellDebuggingService
+    public partial class PowerShellDebuggingService
```
Comment (HuanhuanSunMSFT) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs:20]: Also rename the file to keep it aligned with class name maybe. Same for other renames such as PowerShellBreakpointRecord

**Comment by HuanhuanSunMSFT** [comment]
Looks good after the rename thing fixed
