### PR TITLE
Post Release Fixes to Remote Attaching

### LINKED ISSUE #691: Unexpected Microsoft.PythonTools.Attacher.exe in the running processes
MS build 3.0.1487
VS 2015 RTW build
1. In VS2015, create a powershell script project. You can use the one pasted below.  (the problem is not script specific)
2. Set a breakpoint somewhere in the script. 
3. F5 to stop at the breakpoint
4. Select "Debug->Attach to Process" in the Attach to Process dialog. Leave all settings with default values. Then chose "PowerShell host service" to attach to. Close the dialog
5. Set the focus back in the editor then hit F10 and F5. 
6. Click on stop debugging in the toolbar
7. Repeat steps 3 and 4.

Notice, in the Attach To Process, you will see an extra process named "Microsoft.PythonTools.Attacher.exe", which probably was launched by the PoshTools on the second attach. 

I understand this isn't a typical "Local Attach" scenario, but there was nothing preventing me from doing so. 

Script attached:
# 
# Script.ps1
# 

Get-Service
Get-Process

$var = 'hello'
$number = 1
$numbers = 1,2,3,4,5,6,7,8,9

$debug = "`$computer contains $computer"
$head = "Column`tColumn`tColumn"                            

$filter1 = "name='BITS'"
$computer = 'BITS'
$filter2 = "name=$computer'"
$var = 'hello'
$var | Get-Member
$svc = Get-Service
$svc[0].name
$name = $svc[1].name
$name.Length
$name.ToUpper()

$service = 'bits'
$name = "Service is $service.ToUpper()"
$upper = $name.ToUpper()
$name = "Service is $upper"
Write-Host $name

$name = (Get-Service)[0].name
Write-Host $name

### LINKED ISSUE #693: Should Be Able to Attach to 64bit Regardless of Btiness
Since we no longer examine modules, we can safely attach to any process as long as they are verified as a PowerShell host. This task simply requires removing the following from AttachToProcess:

``` C#
IsWow64Process(process.Handle, out is64Bit);
if (!Environment.Is64BitProcess && is64Bit)
{
    // cannot examine a 64 bit process' modules from a 32 bit process
    return false;
}
```

(remove definition of IsWow64Process as well)

### LINKED ISSUE #694: Prevent Users From Using Remote Attach to Attach to a Local Process
Ideally users should only be using remote attaching to attach to remote processes, not local processes. As such, we should not treat "localhost", "127.0.0.1" or anything similar as a proper qualifier.

### LINKED ISSUE #695: Disable Attaching to the PowerShell Tools Host
We should not allow users to attach to our own host service. PowerShell does let users attach to the original host process, and doing so produces negative/unexpected/bad behavior.

### LINKED ISSUE #696: Local Attach Should Default to PowerShell Only
Visual Studio should not identify processes we say are ok for PowerShell Tools to attach to as debuggable by both our debug engine and the managed code engine.

### LINKED ISSUE #699: Port Support Does Not Always Work
Using ports does not always seem to work. It appears that we are parsing out the port incorrectly.

### PR DESCRIPTION
**Pull request by MrayerMSFT**
Some fixes to things identified as issues with remote attaching:
1. No longer allow users to attach to the host/host service. (resolves #695 and resolves #691)
2. A qualifier with a machine name of "localhost" or "127.0.0.1" will not be treated as a valid qualifier (resolves #694)
3. Took out logic regarding not attaching to a 64 bit process while in 32 bit mode. This ability already exists via the PowerShell cmdlets we are using (resolves #693)
4. Users no longer have to go and select PowerShell Code from the debug type menu. We are now fully marked as incompatible with managed code. (resolves #696 and resolves #691)
5. Port parsing is done correctly now (resolves #699)

### CODE REVIEW

File: PowerShellTools/DebugEngine/Remote/RemoteEnumDebugProcess.cs [hunk 1]
```diff
@@ -98,6 +105,12 @@ public void connect(IDebugPort2 remotePort, bool useSSL)
             }
         }
 
+        private bool isLocalHost()
+        {
```
Comment (ASayre) [inline PowerShellTools/DebugEngine/Remote/RemoteEnumDebugProcess.cs]: 127.0.0.1 is not the only loopback address.  Should use https://msdn.microsoft.com/en-us/library/vstudio/system.net.ipaddress.isloopback(v=vs.100).aspx

File: PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs [hunk 2]
```diff
@@ -403,7 +403,9 @@ private void EnterCredentialedRemoteSession(PowerShell powerShell, string remote
                 return;
             }
 
-            string port = remoteName.Split(':').ElementAtOrDefault(1);
+            string[] addressParts = remoteName.Split(':');
```
Comment (ASayre) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs]: IPv6 will fail here

File: PowerShellTools/Project/SharedProject/ProvideDebugEngineAttribute.cs [hunk 3]
```diff
@@ -60,14 +63,17 @@ class ProvideDebugEngineAttribute : RegistrationAttribute {
             engineKey.SetValue("LoadUnderWOW64", 1);
 
             using (var incompatKey = engineKey.CreateSubkey("IncompatibleList")) {
-                incompatKey.SetValue("guidCOMPlusNativeEng", "{92EF0900-2251-11D2-B72E-0000F87572EF}");
+                // mark the debug engine so you can’t debug with both managed and PowerShell at the same time
```
Comment (ASayre) [inline PowerShellTools/Project/SharedProject/ProvideDebugEngineAttribute.cs:66]: very cool :)

File: PowerShellTools.HostService/ServiceManagement/Debugging/PowerShellDebuggingService.cs [hunk 4]
```diff
@@ -46,6 +46,7 @@ public partial class PowerShellDebuggingService : IPowerShellDebuggingService
         private Version _installedPowerShellVersion;
         private PowerShellDebuggingServiceAttachValidator _validator;
         private bool _useSSL;
+        private int _thisPid;
```
Comment (ASayre) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowerShellDebuggingService.cs]: Minor stylistic nit: avoid this as first word of variable name due to potential confusion with  `this`.

File: PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs (hunk 2 above)
Comment (HuanhuanSunMSFT) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs]: Also, will this handle it correctly if user input something other than an IP address?

Comment (MrayerMSFT) [inline PowerShellTools.HostService/ServiceManagement/Debugging/PowershellDebuggingServiceUtilities.cs]: Working on making sure this is fully compatible with IPv4, IPv6, and other possibilities. As for handling stuff correctly, yes. In the end, everything is handled gracefully. Worst case is that we end up giving something invalid to PowerShell and it can't connect which we catch.

**Comment by ASayre** [comment]
Looks good!
